# Generated by Django 5.2.1 on 2025-05-17 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_asistencia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asistencia',
            name='fecha_entrada',
        ),
        migrations.RemoveField(
            model_name='asistencia',
            name='fecha_salida',
        ),
        migrations.AddField(
            model_name='asistencia',
            name='hora_entrada',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='asistencia',
            name='hora_salida',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
