# Generated by Django 5.2.1 on 2025-05-21 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_remove_asistencia_fecha_entrada_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personaldata',
            name='asistencias',
        ),
        migrations.AlterField(
            model_name='personaldata',
            name='telefono',
            field=models.CharField(max_length=15),
        ),
        migrations.AddField(
            model_name='personaldata',
            name='asistencias',
            field=models.ManyToManyField(blank=True, to='tasks.asistencia'),
        ),
    ]
